// <auto-generated />
using System;
using CarRental.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarRental.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200206115815_initial-two")]
    partial class initialtwo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CarRental.Domain.CarCopy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DetailsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DetailsId");

                    b.ToTable("CarCopy");
                });

            modelBuilder.Entity("CarRental.Domain.CarDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HorsePower")
                        .HasColumnType("int");

                    b.Property<string>("LicensePlate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("CarDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Red",
                            HorsePower = 1337,
                            LicensePlate = "asd123",
                            ManufacturerId = 1,
                            Model = "BMW",
                            Price = 500000
                        },
                        new
                        {
                            Id = 2,
                            Color = "Yellow",
                            HorsePower = 1337,
                            LicensePlate = "asd123",
                            ManufacturerId = 2,
                            Model = "Vovlo",
                            Price = 400000
                        },
                        new
                        {
                            Id = 3,
                            Color = "Yellow",
                            HorsePower = 1337,
                            LicensePlate = "asd123",
                            ManufacturerId = 3,
                            Model = "Vovlo",
                            Price = 400000
                        });
                });

            modelBuilder.Entity("CarRental.Domain.CarManufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(55)")
                        .HasMaxLength(55);

                    b.HasKey("Id");

                    b.ToTable("CarManufacturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Manufacturer = "Hassan AB"
                        },
                        new
                        {
                            Id = 2,
                            Manufacturer = "Volvo"
                        },
                        new
                        {
                            Id = 3,
                            Manufacturer = "BMW"
                        });
                });

            modelBuilder.Entity("CarRental.Domain.CarCopy", b =>
                {
                    b.HasOne("CarRental.Domain.CarDetails", "Details")
                        .WithMany("Copies")
                        .HasForeignKey("DetailsId");
                });

            modelBuilder.Entity("CarRental.Domain.CarDetails", b =>
                {
                    b.HasOne("CarRental.Domain.CarManufacturer", "CarManufacturer")
                        .WithMany("Cars")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
